apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-aps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: git@github.com:ElielBloemer/prueba-tecnica.git
      revision: HEAD
      directories:
      - path: 3-CICD/appset/apps/*/helm
  template:
    metadata:
      name: '{{index .path.segments 3}}'
    spec:
      project: "default"
      source:
        repoURL: git@github.com:ElielBloemer/prueba-tecnica.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 3}}'
      syncPolicy: 
        syncOptions:
        - CreateNamespace=true
        - PruneLast=True
        automated:
          prune: true
        managedNamespaceMetadata:
          labels:
            istio-injection: enabled