version: '3.8'

services:
  db:
    networks:
      - net-db
    container_name: database
    image: postgres:12.0-alpine
    env_file: ./bd/.env.postgres
    volumes:
      - ./bd/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  back:
    networks:
      - net-db
      - net-app
    container_name: back
    build: 
      context: ./backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
     
  frontend:
    networks:
      - net-app
    container_name: front
    build: 
      context: ./frontend
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    depends_on:
      - back  
      
networks:
  net-db:
    driver: bridge
  net-app:
    driver: bridge


