replicaCount: 1

image:
  repository: "ebloemer/nginx-server"
  pullPolicy: IfNotPresent
  tag: "0d24788434d6e9454f2517519771dedbfac146f4"

revisionHistoryLimit: 3

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "nginx-web-server"

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations:
 kubernetes.io/change-cause: ""

podLabels: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  className: "NGINX-INGRES"
  annotations: {}
  hosts:
    - host: "DNS-APP"
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
     cpu: 400m
     memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  failureThreshold: 3
  tcpSocket:
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 1

readinessProbe:
  failureThreshold: 4
  tcpSocket:
    port: 80
  initialDelaySeconds: 6
  periodSeconds: 16
  successThreshold: 2
  timeoutSeconds: 2

startupProbe:
  failureThreshold: 30
  tcpSocket:
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

strategyRollingUpdate:
  maxSurge: 10%
  maxUnavailable: 0  

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 90

env:
  enabled: true
  dataenv:
  - name: ENVIRONMENT
    value: homologacion

secrets:
  enabled: false
  nameSecretK8S: NAME-SECRET-K8S
  key: REG-DEV-API-SERVICES #Nombre del secreto en AWS Secrets Manager
  datasecret:
  - secretKeyName: PASS_SECRET_TEST
    secretKeyAWS: TEST_SECRET_DEV_PASS_AWS
  
volumes: []

volumeMounts: []
nodeSelector:
  nodegroup: aplicacion_medianas

tolerations: []

affinity: {}
