replicaCount: 1

image:
  repository: "ebloemer/nginx-server"
  pullPolicy: IfNotPresent
  tag: "2eab134efabf1776bab62e64b60022faa7ac1d2d"


revisionHistoryLimit: 3

fullnameOverride: nginx-webserver

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations:
 kubernetes.io/change-cause: ""

podLabels: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx-public
  annotations: {}
  hosts:
    - host: web-server-nginx.app.sbx.invertironline.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
     cpu: 2000m
     memory: 1Gi
  requests:
    cpu: 50m
    memory: 150Mi

livenessProbe:
  failureThreshold: 3
  tcpSocket:
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 1

readinessProbe:
  failureThreshold: 4
  tcpSocket:
    port: 80
  initialDelaySeconds: 6
  periodSeconds: 16
  successThreshold: 2
  timeoutSeconds: 2

startupProbe:
  failureThreshold: 30
  tcpSocket:
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

strategyRollingUpdate:
  maxSurge: 25%
  maxUnavailable: 0%

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 90

env:
  enabled: true
  dataenv:
  - name: ENVIRONMENT
    value: homologacion

secrets:
  enabled: false
  nameSecretK8S: nginx-external
  key: SECRETS-WEB-SERVER
  datasecret:
  - secretKeyName: SqlServerSettings__ConnectionString
    secretKeyAWS: SQLSERVERSETTINGS__CONNECTIONSTRING__VALIDATORMARKETDATA_AWS
  
volumes: []

volumeMounts: []

nodeSelector:
  nodegroup: aplicacion_medianas

tolerations: []

affinity: {}
