on:
  push:
    branches:
      - main
    paths:
      - "3-CICD/index.html"
  workflow_dispatch:  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ebloemer/nginx-server:${{ github.sha }} -f 3-CICD/Dockerfile 3-CICD

    - name: Push Docker image
      run: |
        docker push ebloemer/nginx-server:${{ github.sha }}

    - name: Update Helm values file
      run: |
        sed -i "s|tag:.*|tag: \"${{ github.sha }}\"|g" 3-CICD/appset/apps/nginx-web-server/helm/values.yaml

    - name: Commit and Push Updated values.yaml
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add 3-CICD/appset/apps/nginx-web-server/helm/values.yaml
        git commit -m "Update values.yaml with new image tag: ${{ github.sha }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}