name: CI/CD Pipeline for NGINX

on:
  push:
    branches:
      - main
    paths:
      - "index.html"
      - "Dockerfile"
      - "docker-compose.yml"
      - ".github/workflows/ci-cd.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/nginx-server:latest .

    - name: Push Docker image
      run: |
        docker push your-dockerhub-username/nginx-server:latest

    - name: Deploy on remote server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          mkdir -p ~/deploy-scripts
          scp ./scripts/deploy.sh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/deploy-scripts/deploy.sh
          chmod +x ~/deploy-scripts/deploy.sh
          ~/deploy-scripts/deploy.sh ${{ github.sha }}
