name: CI/CD Pipeline for NGINX

on:
  push:
    paths:
      - "index.html"
      - "Dockerfile"
      - "docker-compose.yml"
      - ".github/workflows/ci-cd.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/nginx-server:latest .

    # 4. Push de la imagen a Docker Hub
    - name: Push Docker image
      run: |
        docker push your-dockerhub-username/nginx-server:latest

    # 5. Deploy en el servidor remoto
    - name: Deploy on remote server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker-compose pull
          docker-compose up -d
